### ISSUE TITLE
Strongly typed API - missing Indexes info

### ISSUE THREAD

**Issue by ErikEJ** [Microsoft/DACExtensions#15]
Having just implemented a EF Core DatabaseModel creator using the strongly typed API, I was missing strongly type info for table indexes - is this a bug or by design?

**Comment by kevcunnane** [comment]
It should be there - it's a partial method on TSqlTable in the strongly typed model. See https://github.com/Microsoft/DACExtensions/blob/76f4cf17707f26ee3be47af4fd89a6a5c7feda2d/DacFxStronglyTypedModel/ModelExtensions.cs#L39.

The confusion is this is a "reverse" relationship - the Index references the table it's on. In the loosely typed API you do a `table.GetReferencing(Index.IndexedObject)` to look this up. Worst case you can fall back to that, but the partial method is there when I look at the code.

**Comment by ErikEJ** [comment]
Yes, the Indexes property is there, but the property does not contain very much useful info - should it have been TSqlIndex instead of ISqlIndex ??

**Comment by kevcunnane** [comment]
@lonnybastien any chance you remember the answer to this one, since you wrote it up? Does it require casting to the "compatible" interface/class  type or something? I'm not 100% clear on what the desired next steps would be to get the right index type. There are a bunch of different variants, how can we help Erik query the properties he cares about here?

```
				case "ISqlIndex":
					yield return TSqlColumnStoreIndex.TypeClass;
					yield return TSqlIndex.TypeClass;
					yield return TSqlSelectiveXmlIndex.TypeClass;
					yield return TSqlSpatialIndex.TypeClass;
					yield return TSqlTableTypeIndex.TypeClass;
					yield return TSqlXmlIndex.TypeClass;
					break;
```

**Comment by lonnybastien** [comment]
So the property returns the interface as many different index types can be returned by that property. The interface ISqlIndex represents that abstraction. To get the details of the actual index, you will need to down cast to the specific index type as you suggested.

**Comment by ErikEJ** [comment]
Thanks, Lonny, that was it (casting to TSqlIndex) - now I have all the nice properties!

**Comment by ErikEJ** [comment]
Long live the strongly typed API!

https://github.com/ErikEJ/SqlCeToolbox/commit/8379ab00ca92f01b64663c2aa7cca02829ca65e1

Maybe expose a collection for each of the Index types, to make them  more discoverable?
