### ISSUE TITLE
Missing Microsoft.SqlServer.DacFx.x86 package for DAC tools version 150

### ISSUE THREAD

**Issue by bojingo** [Microsoft/DACExtensions#21]
Not sure this is the right place/repo for this issue, but it is the closest one I can find. Hopefully someone can route this to the right place/person/team...

I have a SQL Azure Database deployment that depends on custom `DeploymentPlanModifier`. It references this NuGet package: https://www.nuget.org/packages/Microsoft.SqlServer.DacFx.x86/140.3881.1

Well, now our build agents and Azure Database supports compatibility level 150 so our release process is using the 150 DAC tools (located in `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\150` for us). This version of the tools won't load our custom plan modifier.

We get this error:

```
Error Deploy72002: DeploymentContributor 'XXX' threw exception. Message is: 'Could not load file or assembly 'Microsoft.Data.Tools.Schema.Sql, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'
DeploymentContributor 'XXX' threw exception. Message is: 'Could not load file or assembly 'Microsoft.Data.Tools.Schema.Sql, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'
Could not load file or assembly 'Microsoft.Data.Tools.Schema.Sql, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
The Azure SQL DACPAC task failed. SqlPackage.exe exited with code 1.Check out how to troubleshoot failures at https://aka.ms/sqlazuredeployreadme#troubleshooting-
```

All the assemblies I need are in the DAC 150 tools folder, but this isn't 2001 where we copy DLLs around manually. Give me an updated NuGet package.

**Comment by pensivebrian** [comment]
We've finally shipped nuget versions that support compat level 150. Sorry for the delay.

https://www.nuget.org/packages/Microsoft.SqlServer.DacFx.x64/150.4200.1
https://www.nuget.org/packages/Microsoft.SqlServer.DacFx.x86/150.4200.1
