### ISSUE TITLE
Supplying a DeploymentPlanModifier Directly

### ISSUE THREAD

**Issue by mattnischan** [microsoft/DACExtensions#22]
Currently in DacFx, one is able to add a DeploymentPlanModifier to the deployment by specifying the string ID in DeploymentOptions:

```csharp
var options = new DeploymentOptions 
{ 
    AdditionalDeploymentContributors = "Some.Id.Here"
};
```

However, that requires that there be a separate DLL either alongside or in a hardcoded extensions folder, which I currently cannot do. Is there any way of directly supplying the API with either the type of the plan modifier or even an instance to skip the whole assembly search process?

I've been slogging through ILSpy for a while and this looks buried way in there, so I'm not immediately seeing a way of injecting anything into the deploy process. There's an awful lot of internal only API.

As a side note, is there any plan to open source DacFx? There's the opportunity to build some really cool tooling on top but it's pretty hard to get at some of the code surface.

**Comment by pensivebrian** [comment]
This ability is now available in the lastest DacFx 18.3.1 release. Deployment contributors will be loaded from the same directory as the target .dacpac being deployed, the Extensions directory relative to the sqlpackage.exe binary (or DacFx assemblies), and the /p:AdditionalDeploymentContributorPaths=(STRING) parameter added to sqlpackage where additional directory locations can be specified.

**Comment by mattnischan** [comment]
Hi @pensivebrian,

We are not using sqlpackage.exe. Is there a way to accomplish this as a library consumer?

**Comment by pensivebrian** [comment]
DeploymentOptions now has a parameter to specify paths to load additional deployment contributors. This should be a semi-colon delimited list of values for multiple folders.
```
var options = new DeploymentOptions 
{ 
    AdditionalDeploymentContributorPaths= @"C:\PathToFolderWithContributors"
};
```

Thanks for the feedback about open sourcing DacFx. It's high on our list of libraries to open source, but we don't have any timelines or work scheduled to make this happen as of yet. Adding @dzsquared as an FYI,

**Comment by mattnischan** [comment]
Sounds good, much appreciated!
