### ISSUE TITLE
DacServices.ExportBacpac: Intermittent errors when extracting a package from a database with numbered stored procedures

### ISSUE THREAD

**Issue by aecucu** [microsoft/DACExtensions#56]
DacFX.x64 version: 150.4897.1
SQL Server: SQL Server 2017 (v14.0.2027.2)
Database compatibility level: 110
Data Migration Assistant report: No migration blockers
DacExportOptions: [CommandTimeout: 0s, SchemaModelStorage: File, TargetEngineVersion: Latest, VerifyFullTextDocumentTypesSupported: True, LongRunningCommandTimeout: 0s, DatabaseLockTimeout: 60s, IgnoreIndexesStatisticsOnEnclaveEnabledColumns:False, TempDirectoryForTableData: '']

Sample error message: "Error SQL71501: Error validating element [dbo].[hideObject]: Procedure: [dbo].[hideObject] has an unresolved reference to object [dbo].[checkRights].[1]."

Please note that the numbered stored procedure checkRights;1 exists, the caller proc
[stdout_bug_export.txt](https://github.com/microsoft/DACExtensions/files/5673797/stdout_bug_export.txt)
edure uses the syntax exec "checkRights;1" (n.b., no dbo-prefix) and that the task fails only intermittently on the database to be exported and other databases with the same schema.

**Comment by ErikEJ** [comment]
Could you share a sample CREATE PROCEDURE statement?

**Comment by aecucu** [comment]
@ErikEJ Thank you for the reply. 
I have attached a copy of the requested script.
[hideObject.sql.txt](https://github.com/microsoft/DACExtensions/files/5673885/hideObject.sql.txt)

**Comment by ErikEJ** [comment]
I meant for checkrights;1

**Comment by aecucu** [comment]
@ErikEJ Thank you for your interest!
Here is the requested file:
[checkRights.sql.txt](https://github.com/microsoft/DACExtensions/files/5673995/checkRights.sql.txt)

The execution of the call to checkRights;1 in SSMS:
DECLARE	@return_value int

EXEC	@return_value = checkRights;1
		@v_rights = N'''a''',
		@v_ucid = 1,
		@v_oid = 12,
		@v_uid = 1

SELECT	'Return Value' = @return_value

"Msg 50000, Level 11, State 1, Procedure checkRights, Line 38 [Batch Start Line 2]
User with id 1 does not have the appropriate rights ('a') on object with id 12. Access denied"

**Comment by ErikEJ** [comment]
I think you have issues because this feature (numbered procedures) is no longer supported, and was deprecated in 2008: https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2008/ms143729(v=sql.100)?redirectedfrom=MSDN

**Comment by aecucu** [comment]
@ErikEJ Thank you for your reply!
We are aware of the deprecated status of the feature, but it is still working with the database at compatibility level 110. What is bothering me most is the intermittent nature of the failure to validate the model during the creation of the BACPAC. Our workflow is the following: Create a new database from a regular database backup, export the database as BACPAC, delete database. Most of the time, the BACPAC will be produced as expected, but from time to time this validation error occurs. I could not find yet an explanation for this behaviour.

**Comment by ErikEJ** [comment]
And this always takes place on the exact same machine with the exact same DacFX binaries?

**Comment by aecucu** [comment]
@ErikEJ The problem has occurred intermittently also with older versions of the DacFX x64 binaries (v150.4384.2 and 15.0.4538.1) and on different machines: Windows 10 development machines and Azure VMs based on custom images with WS 2016 Datacenter and SQL Server 2017 Standard in test and production environments). In testing and production, the issue has occurred only a couple of times so far.
